language: python
python: "3.7"
env:
  - TOX_ENV=py37
  - TOX_ENV=black
  - TOX_ENV=flake8
  - TOX_ENV=mypy
matrix:
  include:
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "3.8"
      env: TOX_ENV=py38
install:
  - pip uninstall virtualenv
  - pip install tox
script:
  - tox -e $TOX_ENV
